includes:
  - https://github.ibm.com/cloud-docs/billing-usage
  - https://github.ibm.com/cloud-docs/secure-enterprise
  - https://github.ibm.com/cloud-docs/satellite
  - https://github.ibm.com/cloud-docs/overview
  - https://github.ibm.com/cloud-docs/power-iaas
  - https://github.ibm.com/cloud-docs/dl
  - https://github.ibm.com/cloud-docs-solutions/industry-ref-arch
  - https://github.ibm.com/cloud-docs-solutions/enterprise-account-architecture
  - https://github.ibm.com/cloud-docs/enterprise-management